export const GET_ERRORS = "GET_ERRORS";

///********** USER ********/ 

//Auth
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Find User Details
export const USER_INFO_LOADING = "USER_INFO_LOADING";
export const SET_USER_DETAILS = "SET_USER_DETAILS";

//Edit User Details
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const USER_EDIT_LOADING = "USER_EDIT_LOADING";

///********** CLIENT ********/ 

//Create Client Details
export const CLIENT_CREATE_LOADING = "CLIENT_CREATE_LOADING";
export const CREATE_CLIENT_DETAILS = "CREATE_CLIENT_DETAILS";

//Edit Client Details
export const CLIENT_EDIT_LOADING = "CLIENT_EDIT_LOADING";
export const UPDATE_CLIENT_DETAILS = "UPDATE_CLIENT_DETAILS";

//Remove Client
export const CLIENT_REMOVE_LOADING = "CLIENT_REMOVE_LOADING";
export const REMOVE_CLIENT_DETAILS = "REMOVE_CLIENT_DETAILS";

///********** PROJECT ********/ 

//Find Project Details
export const FIND_PROJECT_LOADING = "FIND_PROJECT_LOADING";
export const FIND_PROJECT_DETAILS = "FIND_PROJECT_DETAILS";

//Find All Project Details
export const FINDALL_PROJECT_LOADING = "FINDALL_PROJECT_LOADING";
export const FINDALL_PROJECT_DETAILS = "FINDALL_PROJECT_DETAILS";

//Create Project Details
export const PROJECT_CREATE_LOADING = "PROJECT_CREATE_LOADING";
export const CREATE_PROJECT_DETAILS = "CREATE_PROJECT_DETAILS";

//Edit Project Details
export const UPDATE_PROJECT_DETAILS = " UPDATE_PROJECT_DETAILS";
export const PROJECT_EDIT_LOADING = "PROJECT_EDIT_LOADING";

export const UPDATE_PROJECTDROPS_DETAILS = " UPDATE_PROJECTDROPS_DETAILS";
export const PROJECTDROPS_EDIT_LOADING = "PROJECTDROPS_EDIT_LOADING";

//Remove Project
export const PROJECT_REMOVE_LOADING = "PROJECT_REMOVE_LOADING";
export const REMOVE_PROJECT_DETAILS = "REMOVE_PROJECT_DETAILS";

///********** LOG ********/ 

//Create Log Details
export const LOG_CREATE_LOADING = "LOG_CREATE_LOADING";
export const CREATE_LOG_DETAILS = "CREATE_LOG_DETAILS";

//Edit Log Details
export const UPDATE_LOG_DETAILS = "UPDATE_LOG_DETAILS";
export const LOG_EDIT_LOADING = "LOG_EDIT_LOADING";

//Remove Log
export const LOG_REMOVE_LOADING = "LOG_REMOVE_LOADING";
export const REMOVE_LOG_DETAILS = "REMOVE_LOG_DETAILS";
